# Generated by Django 5.0.1 on 2024-02-11 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedido', '0007_alter_itemcotacao_empresa'),
        ('Produto', '0001_initial'),
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo_conferencia', models.CharField(choices=[('1', 'palete fechado'), ('2', 'fechado misto'), ('3', 'Volume'), ('4', 'Fração')], max_length=100)),
                ('nf', models.IntegerField()),
                ('fluxo', models.CharField(choices=[('1', 'Entrada'), ('2', 'Saida')], max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to='empresa.empresa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to='Pedido.pedidocompra')),
            ],
            options={
                'verbose_name': 'Conferencia',
                'verbose_name_plural': 'Conferências',
                'db_table': 'Conferencia',
                'unique_together': {('id', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='AprovacaoConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes_conferencia', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios')),
                ('conferencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes_conferencia', to='Armazem.conferencia')),
            ],
            options={
                'verbose_name': 'Aprovação de Conferência',
                'verbose_name_plural': 'Aprovações de Conferências',
                'db_table': 'Aprovacao_conferencia',
            },
        ),
        migrations.CreateModel(
            name='ItensConferencia',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_conferencias', to='Produto.produto')),
                ('conferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_conferencias', to='Armazem.conferencia')),
            ],
            options={
                'verbose_name': 'Item_conferencia',
                'verbose_name_plural': 'Itens_conferencias',
                'db_table': 'Item_Conferencia',
            },
        ),
        migrations.CreateModel(
            name='MOVIMENTACAO',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(choices=[('1', 'Entrada'), ('2', 'Saida'), ('3', 'Conferencia_entrada'), ('4', 'Conferencia_saida'), ('5', 'Transferência')], max_length=30)),
                ('tipo_conferencia', models.CharField(choices=[('1', 'palete fechado'), ('2', 'fechado misto'), ('3', 'Volume'), ('4', 'Fração')], max_length=100)),
                ('date', models.DateField()),
                ('aprovado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='empresa.empresa')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentações', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentaçao',
                'verbose_name_plural': 'Movimentações',
                'db_table': 'Movimentacao',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_interno', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Produto.produto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresa.empresa')),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Armazem.movimentacao')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Posicao',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('rua', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=30)),
                ('predio', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=30)),
                ('nivel', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28')], max_length=30)),
                ('sequencia', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28')], max_length=30)),
                ('capacidade_peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('capacidade_volume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alto_valor', models.BooleanField(default=False)),
                ('controlados', models.BooleanField(default=False)),
                ('pesados', models.BooleanField(default=False)),
                ('blocados', models.BooleanField(default=False)),
                ('miudezas', models.BooleanField(default=False)),
                ('refrigerados', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Posição',
                'verbose_name_plural': 'Posições',
                'db_table': 'Posicao',
            },
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armazem.posicao'),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='empresa.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='Produto.produto')),
                ('posicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armazem.posicao')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'db_table': 'Estoque',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('controle_estoque', models.CharField(choices=[('FIFO', '1'), ('FEFO', '2'), ('LIFO', '3')], max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': 'Unidade',
                'unique_together': {('nome', 'empresa')},
            },
        ),
        migrations.AddField(
            model_name='posicao',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='Armazem.unidade'),
        ),
        migrations.CreateModel(
            name='Doca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(max_length=50)),
                ('recebimento', models.BooleanField(default=False)),
                ('expedicao', models.BooleanField(default=False)),
                ('outras', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docas', to='empresa.empresa')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docas', to='Armazem.unidade')),
            ],
            options={
                'verbose_name': 'Doca',
                'verbose_name_plural': 'Docas',
                'db_table': 'Doca',
            },
        ),
        migrations.AlterUniqueTogether(
            name='movimentacao',
            unique_together={('id', 'empresa')},
        ),
        migrations.CreateModel(
            name='Transitorio',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_interno', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=30)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_transitorios', to='Produto.produto')),
                ('conferencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_transitorios', to='Armazem.conferencia')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_transitorios', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Transitorio',
                'verbose_name_plural': 'Transitórios',
                'db_table': 'Transitorio',
                'unique_together': {('id', 'empresa')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='posicao',
            unique_together={('nome', 'empresa')},
        ),
    ]
