# Generated by Django 5.0.1 on 2024-02-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armazem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitorio',
            name='status',
        ),
        migrations.AddField(
            model_name='transitorio',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
