# Generated by Django 5.0.1 on 2024-02-01 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Armazem', '0001_initial'),
        ('Pedido', '0001_initial'),
        ('Produto', '0001_initial'),
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conferencia',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to='Pedido.pedidocompra'),
        ),
        migrations.AddField(
            model_name='doca',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docas', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='Produto.produto'),
        ),
        migrations.AddField(
            model_name='item',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Produto.produto'),
        ),
        migrations.AddField(
            model_name='item',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='itensconferencia',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_conferencias', to='Produto.produto'),
        ),
        migrations.AddField(
            model_name='itensconferencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_conferencias', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='conferencia',
            name='itens_conferencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias', to='Armazem.itensconferencia'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentações', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='movimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Armazem.movimentacao'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armazem.posicao'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armazem.posicao'),
        ),
        migrations.AddField(
            model_name='conferencia',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Armazem.posicao'),
        ),
        migrations.AddField(
            model_name='transitorio',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_transitorios', to='Produto.produto'),
        ),
        migrations.AddField(
            model_name='transitorio',
            name='conferencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_transitorios', to='Armazem.conferencia'),
        ),
        migrations.AddField(
            model_name='transitorio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_transitorios', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='posicao',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='Armazem.unidade'),
        ),
        migrations.AddField(
            model_name='doca',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docas', to='Armazem.unidade'),
        ),
        migrations.AlterUniqueTogether(
            name='movimentacao',
            unique_together={('id', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='conferencia',
            unique_together={('id', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='transitorio',
            unique_together={('id', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='unidade',
            unique_together={('nome', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='posicao',
            unique_together={('nome', 'empresa')},
        ),
    ]
