# Generated by Django 5.0.1 on 2024-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armazem', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='controle_estoque',
            field=models.CharField(choices=[('FIFO', '1'), ('FEFO', '2'), ('LIFO', '3')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
