# Generated by Django 5.0.1 on 2024-02-12 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Armazem', '0002_remove_transitorio_status_transitorio_aprovado'),
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transitorio',
            old_name='aprovado',
            new_name='aprovado_conferencia',
        ),
        migrations.AlterUniqueTogether(
            name='transitorio',
            unique_together={('id', 'empresa', 'codigo_interno')},
        ),
        migrations.AddField(
            model_name='transitorio',
            name='aprovado_posicao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transitorio',
            name='movimentacoes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_transitorios', to='Armazem.movimentacao'),
        ),
        migrations.AddField(
            model_name='transitorio',
            name='status',
            field=models.CharField(choices=[('1', 'Aguardando Aprovação'), ('2', 'Conferencia Aprovada'), ('3', 'Conferencia Rejeitada'), ('4', 'Etiquetando'), ('5', 'Armazenado'), ('6', 'Transferido'), ('7', 'Picking Realizado'), ('8', 'Aguardando Conferencia saida'), ('9', 'Baixado')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transitorio',
            name='usuario_armazenamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens_transitorios_armazenamento', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transitorio',
            name='usuario_conferencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens_transitorios_conferencia', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
