# Generated by Django 5.0.1 on 2024-02-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0002_configuracao_email_forncedor_automatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='quantidade_cotacao',
            field=models.IntegerField(default=3),
        ),
    ]
