# Generated by Django 5.0.1 on 2024-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0003_configuracao_quantidade_cotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='aviso_recebimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='email_forncedor_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='geracao_pedido_auto',
            field=models.BooleanField(default=False),
        ),
    ]
