# Generated by Django 5.0.1 on 2024-02-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0005_configuracao_responsavel_almoxarifado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='aviso_recebimento',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='quantidade_cotacao',
        ),
        migrations.RemoveField(
            model_name='configuracao',
            name='responsavel_almoxarifado',
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='email_forncedor_automatico',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='geracao_pedido_auto',
            field=models.BooleanField(),
        ),
    ]
