# Generated by Django 5.0.1 on 2024-01-26 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produto', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operador', models.CharField(max_length=30)),
                ('solicitante', models.CharField(max_length=30)),
                ('observacao', models.TextField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('estimativa_valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_de_entrega', models.IntegerField(blank=True, default=0, null=True)),
                ('nf', models.FileField(blank=True, null=True, upload_to='')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_compras', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Solicitacão Compra',
                'verbose_name_plural': 'Solicitacões Compras',
                'db_table': 'Pedido_compra',
                'unique_together': {('id', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_interno', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_de_entrega', models.IntegerField(blank=True, default=0, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido_compra', to='Produto.produto')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido_compra', to='Pedido.pedidocompra')),
            ],
            options={
                'verbose_name': 'Item_Solicitacão',
                'verbose_name_plural': 'Itens_Solicitações',
                'db_table': 'Item_Pedido_Compra',
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operador', models.CharField(max_length=30)),
                ('fornecedor', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=30)),
                ('email_contato', models.EmailField(max_length=254)),
                ('observacao', models.TextField(blank=True, max_length=200, null=True)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_de_entrega', models.IntegerField(blank=True, default=0, null=True)),
                ('orcamento', models.FileField(upload_to='orcamento/')),
                ('justificativa', models.TextField(blank=True, max_length=200, null=True)),
                ('fechado', models.BooleanField(default=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotações', to='empresa.empresa')),
                ('pedido_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='Pedido.pedidocompra')),
            ],
            options={
                'verbose_name': 'Cotacão',
                'verbose_name_plural': 'Cotações',
                'db_table': 'Cotacao',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operador', models.CharField(max_length=30)),
                ('solicitante', models.CharField(max_length=30)),
                ('observacao', models.TextField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Solicitacão Compra',
                'verbose_name_plural': 'Solicitacões Compras',
                'db_table': 'Solicitacao_compra',
                'unique_together': {('id', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_interno', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitações', to='Produto.produto')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitacões', to='Pedido.solicitacao')),
            ],
            options={
                'verbose_name': 'Item_Solicitacão',
                'verbose_name_plural': 'Itens_Solicitações',
                'db_table': 'Item_Solicitacao',
            },
        ),
    ]
