# Generated by Django 5.0.1 on 2024-02-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AprovacaoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
            ],
            options={
                'verbose_name': 'Aprovação de Solicitação',
                'verbose_name_plural': 'Aprovações de Solicitações',
                'db_table': 'Aprovacao_Solicitacao_de_Compra',
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operador', models.CharField(max_length=30)),
                ('fornecedor', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=30)),
                ('email_contato', models.EmailField(max_length=254)),
                ('observacao', models.TextField(blank=True, max_length=200, null=True)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_de_entrega', models.IntegerField(blank=True, default=0, null=True)),
                ('orcamento', models.FileField(blank=True, null=True, upload_to='arquivo/orcamento')),
                ('justificativa', models.TextField(blank=True, max_length=200, null=True)),
                ('fechado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cotacão',
                'verbose_name_plural': 'Cotações',
                'db_table': 'Cotacao',
            },
        ),
        migrations.CreateModel(
            name='ItemAvulso',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='imagem_solicitacao')),
                ('fornecedor_indicado', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Item Avulso Solicitação ',
                'verbose_name_plural': 'Itens Avulsos Solictação',
                'db_table': 'Item_Avulso_Solicitacao',
            },
        ),
        migrations.CreateModel(
            name='ItemAvulsoPedido',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fornecedor_indicado', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Item Avulso Pedido ',
                'verbose_name_plural': 'Itens Avulsos Pedido',
                'db_table': 'Item_Avulso_Pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemCotacao',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('codigo_interno', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empresa', models.CharField(max_length=30)),
                ('ultimo_preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Item_cotacao',
                'verbose_name_plural': 'Itens_cotacao',
                'db_table': 'Item_cotacao',
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_de_entrega', models.IntegerField(blank=True, default=0, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Item Pedido de Compra',
                'verbose_name_plural': 'Itens Pedido de Compra',
                'db_table': 'Item_Pedido_Compra',
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitacao',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Item_Solicitacão',
                'verbose_name_plural': 'Itens_Solicitações',
                'db_table': 'Item_Solicitacao',
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solicitante', models.CharField(max_length=30)),
                ('observacao', models.TextField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('estimativa_valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo_de_entrega', models.IntegerField(blank=True, default=0, null=True)),
                ('nf', models.FileField(blank=True, null=True, upload_to='arquivo/nf')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'db_table': 'Pedido_compra',
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Atualização')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacao', models.TextField(blank=True, max_length=200, null=True)),
                ('urgencia', models.BooleanField(default=False, verbose_name='Urgente')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='justificativa')),
                ('valor_estimado', models.BooleanField(blank=True, default=False, null=True)),
                ('descricao', models.TextField(verbose_name='observação')),
            ],
            options={
                'verbose_name': 'Solicitacão Compra',
                'verbose_name_plural': 'Solicitacões Compras',
                'db_table': 'Solicitacao_compra',
            },
        ),
    ]
