# Generated by Django 5.0.1 on 2024-02-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
