# Generated by Django 5.0.1 on 2024-01-29 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_alter_itempedidocompra_options_and_more'),
        ('Produto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemavulso',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='itemsolicitacao',
            name='atualizacao',
        ),
        migrations.RemoveField(
            model_name='itemsolicitacao',
            name='codigo_interno',
        ),
        migrations.RemoveField(
            model_name='itemsolicitacao',
            name='total_estimado',
        ),
        migrations.RemoveField(
            model_name='itemsolicitacao',
            name='ultimo_preco_unit',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='operador',
        ),
        migrations.AddField(
            model_name='itemavulso',
            name='imagem',
            field=models.ImageField(blank=True, default='', null=True, upload_to='imagem_solicitacao'),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='orcamento',
            field=models.FileField(blank=True, null=True, upload_to='arquivo/orcamento'),
        ),
        migrations.AlterField(
            model_name='itemsolicitacao',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitacoes', to='Produto.produto'),
        ),
        migrations.AlterField(
            model_name='itemsolicitacao',
            name='solicitacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_solicitacoes', to='Pedido.solicitacao'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='nf',
            field=models.FileField(blank=True, null=True, upload_to='arquivo/nf'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solictacoes_de_compra', to=settings.AUTH_USER_MODEL),
        ),
    ]
