# Generated by Django 5.0.1 on 2024-02-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprovacaosolicitacao',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to='Pedido.solicitacao'),
        ),
    ]
