# Generated by Django 5.0.1 on 2024-01-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_remove_itemavulso_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemavulsopedido',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='itemavulsopedido',
            name='solicitacao',
        ),
        migrations.RemoveField(
            model_name='itempedidocompra',
            name='atualizacao',
        ),
        migrations.RemoveField(
            model_name='itempedidocompra',
            name='codigo_interno',
        ),
        migrations.AddField(
            model_name='itemavulsopedido',
            name='pedido_compra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido_avulso', to='Pedido.pedidocompra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemavulso',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_avulso', to='Pedido.solicitacao'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Criação'),
        ),
        migrations.AlterField(
            model_name='itempedidocompra',
            name='pedido_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido_compra', to='Pedido.pedidocompra'),
        ),
    ]
