# Generated by Django 5.0.1 on 2024-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_alter_solicitacao_valor_estimado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotacao',
            old_name='valor_pedido',
            new_name='valor_cotacao',
        ),
        migrations.RemoveField(
            model_name='itemcotacao',
            name='codigo_interno',
        ),
        migrations.RemoveField(
            model_name='itemcotacao',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='itemcotacao',
            name='ultimo_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
