# Generated by Django 5.0.1 on 2024-02-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0004_rename_valor_pedido_cotacao_valor_cotacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='condicao_comercial',
            field=models.CharField(choices=[('1', 'A vista'), ('2', 'A prazo')], default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotacao',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
