# Generated by Django 5.0.1 on 2024-02-05 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0005_cotacao_condicao_comercial_cotacao_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotacao',
            name='cotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_cotacoes', to='Pedido.cotacao'),
        ),
    ]
