# Generated by Django 5.0.1 on 2024-02-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0005_alter_aprovacaosolicitacao_justificativa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocompra',
            name='atualizacao',
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Criação'),
        ),
    ]
