# Generated by Django 5.0.1 on 2024-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0006_alter_itemcotacao_cotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotacao',
            name='empresa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
